plugins {
    id "org.jetbrains.kotlin.jvm" version "1.9.25" apply false
    id "org.jetbrains.kotlin.android" version "1.9.25" apply false
    id "com.android.application" version "8.7.2" apply false
}

ext {
    appName = "vaniaGame"
    gdxVersion = "1.13.1"
    box2DLightsVersion = "1.5"
    ashleyVersion = "1.7.4"
    aiVersion = "1.8.2"
}

allprojects {
    version = "1.0"

    repositories {
        mavenLocal()
        mavenCentral()
        google()
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    }
}

configure([project(":core"), project(":desktop")]) {
    apply plugin: "org.jetbrains.kotlin.jvm"
    apply plugin: "idea"
    apply plugin: "eclipse"

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions.jvmTarget = "21"
    }
}