apply plugin: "application"

sourceSets.main.java.srcDirs = ["src/"]

ext.mainClassName = "com.onimurasame.vania.desktop.DesktopLauncherKt"
ext.assetsDir = file("../android/assets")

dependencies {
    implementation project(":core")
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    runtimeOnly "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    runtimeOnly "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
    runtimeOnly "com.badlogicgames.gdx:gdx-bullet-platform:$gdxVersion:natives-desktop"
}

application {
    mainClass = project.mainClassName
}

tasks.named("run", JavaExec).configure {
    workingDir = project.assetsDir
    standardInput = System.in
}

tasks.register("debug", JavaExec) {
    dependsOn tasks.classes
    mainClass = project.mainClassName
    classpath = sourceSets.main.runtimeClasspath
    workingDir = project.assetsDir
    standardInput = System.in
    debug = true
}

tasks.register("dist", Jar) {
    archiveClassifier = "all"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes "Main-Class": project.mainClassName
    }
    from sourceSets.main.output
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

eclipse {
    project {
        name = appName + "-desktop"
        linkedResource name: "assets", type: "2", location: "PARENT-1-PROJECT_LOC/android/assets"
    }
}
